### ISSUE TITLE
Invalid type of children property

### ISSUE THREAD

**Issue by bikeshedder** [solidui/solid-transition-group#4]
Given the following code...
```html
<Transition><div/></Transition>
```
...the TS compiler inside VSCode complains:
```
Type 'Element' is not assignable to type '(Element & (string | number | boolean | Node | ArrayElement | FunctionElement | null)) | undefined'.
  Type 'null' is not assignable to type '(Element & (string | number | boolean | Node | ArrayElement | FunctionElement | null)) | undefined'.ts(2322)
Transition.d.ts(16, 5): The expected type comes from property 'children' which is declared here on type 'IntrinsicAttributes & TransitionProps & { children?: Element; }'
```

Looking at the `Transition.d.ts` I found it accepting an `Element` rather than `JSX.Element`. Is this correct? When I change the `TransitionProps` as follows the error goes away:
```diff
-    children?: Element;
+    children?: JSX.Element;
```

**Comment by ryansolid** [comment]
Ah TypeScript.. I was trying to be explicit that it wasn't just any JSX element but one that was a DOM element. Like a div.  I didn't check the TS but I was hoping narrowing would work but I guess the problem is TS doesn't realize that `<div>` is in fact an `Element`.. only that it could be an `Element`. I guess I should just change it and accept the Types won't be specific enough here.

**Comment by bikeshedder** [comment]
Cool. Thanks a lot for the 0.0.6 release! :+1:
